fwv_api:
    resource: "@FWVApiBundle/Resources/config/routing.yml"
    prefix:   /api

api_login_check:
    path: /api/login_check

fwv_manager:
    resource: "@FWVManagerBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FWVUserBundle/Resources/config/routing.xml"