fwv_api_check:
    path:     /check
    defaults: { _controller: FWVApiBundle:Default:check }

fwv_api_server_running:
    path:     /isServerRunning
    defaults: { _controller: FWVApiBundle:Default:isServerRunning }

fwv_api_server_start:
    path:     /stopServer
    defaults: { _controller: FWVApiBundle:Default:stopServer }
