fwv_api_check:
    path:     /check
    defaults: { _controller: FWVApiBundle:Default:check }

fwv_api_server_running:
    path:     /isServerRunning
    defaults: { _controller: FWVApiBundle:Default:isServerRunning }

fwv_api_server_stop:
    path:     /stopServer
    defaults: { _controller: FWVApiBundle:Default:stopServer }

fwv_api_server_start:
    path:     /startServer
    defaults: { _controller: FWVApiBundle:Default:startServer }

fwv_api_get_logs:
    path:     /getLogs
    defaults: { _controller: FWVApiBundle:Default:getLogs }
